{"name": "test_add_new_address_with_invalid_credentials[shashi kumar-7073052300-845305-3-singhpur haraiya raxaul-address already exist address]", "status": "passed", "attachments": [{"name": "failed_test", "source": "6cf01af9-7e96-45fa-9c09-7f900309d2be-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "e42a0e8d-23da-4932-bda7-abebfa56eb53-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "fullname", "value": "'shashi kumar'"}, {"name": "mobileNumber", "value": "'7073052300'"}, {"name": "pincode", "value": "'845305'"}, {"name": "flate_house", "value": "'3'"}, {"name": "area", "value": "'singhpur haraiya raxaul'"}, {"name": "expected", "value": "'address already exist address'"}], "start": 1707803172671, "stop": 1707803194712, "uuid": "727a0a36-8c6a-4bfb-a480-1502eb992db5", "historyId": "2663a9d7c542d6ead732aa40db990b8b", "testCaseId": "74cb6ea51f8d450d4cb0ff6392836647", "fullName": "testCases.test_address.TestAddress#test_add_new_address_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_address"}, {"name": "subSuite", "value": "TestAddress"}, {"name": "host", "value": "shashi-Aspire-A715-41G"}, {"name": "thread", "value": "89146-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_address"}]}