{"name": "test_add_new_address_with_invalid_credentials[shashi kumar-7073052300-845305-3-singhpur haraiya raxaul-address already exist address]", "status": "passed", "attachments": [{"name": "failed_test", "source": "e8700c6a-aa50-4d56-b7d2-d8cf93ca080a-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "18863b20-9d4c-4f0d-8a25-dc18373783ef-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "fullname", "value": "'shashi kumar'"}, {"name": "mobileNumber", "value": "'7073052300'"}, {"name": "pincode", "value": "'845305'"}, {"name": "flate_house", "value": "'3'"}, {"name": "area", "value": "'singhpur haraiya raxaul'"}, {"name": "expected", "value": "'address already exist address'"}], "start": 1707890181091, "stop": 1707890200346, "uuid": "44ed8427-783c-459e-a5d8-c7b83026d4dc", "historyId": "2663a9d7c542d6ead732aa40db990b8b", "testCaseId": "74cb6ea51f8d450d4cb0ff6392836647", "fullName": "testCases.test_address.TestAddress#test_add_new_address_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_address"}, {"name": "subSuite", "value": "TestAddress"}, {"name": "host", "value": "shashi-Aspire-A715-41G"}, {"name": "thread", "value": "27537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_address"}]}