{"name": "test_add_new_address_with_invalid_credentials[shashi kumar-7073052300-845305-3-singhpur haraiya raxaul-address already exist address]", "status": "passed", "attachments": [{"name": "failed_test", "source": "83c4d15a-da8e-4b34-ac69-607ce4fa7b96-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "054e7ab0-91ee-44d1-bea3-7d26babef31f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "fullname", "value": "'shashi kumar'"}, {"name": "mobileNumber", "value": "'7073052300'"}, {"name": "pincode", "value": "'845305'"}, {"name": "flate_house", "value": "'3'"}, {"name": "area", "value": "'singhpur haraiya raxaul'"}, {"name": "expected", "value": "'address already exist address'"}], "start": 1707975909446, "stop": 1707975922763, "uuid": "ef42293a-88d0-404f-90e8-e547ab05bf56", "historyId": "2663a9d7c542d6ead732aa40db990b8b", "testCaseId": "74cb6ea51f8d450d4cb0ff6392836647", "fullName": "testCases.test_address.TestAddress#test_add_new_address_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_address"}, {"name": "subSuite", "value": "TestAddress"}, {"name": "host", "value": "shashi-Aspire-A715-41G"}, {"name": "thread", "value": "109651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_address"}]}